<a href="https://colab.research.google.com/github/olihile84-tech/exercise-syntax-variables-and-numbers/blob/main/Reading_Writing_Creating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install git+https://github.com/Kaggle/learntools.git

Collecting git+https://github.com/Kaggle/learntools.git
  Cloning https://github.com/Kaggle/learntools.git to /tmp/pip-req-build-6hccy7b6
  Running command git clone --filter=blob:none --quiet https://github.com/Kaggle/learntools.git /tmp/pip-req-build-6hccy7b6
  Resolved https://github.com/Kaggle/learntools.git to commit a0c08ac1fa73dd42ba4aecf2cce045752f14f72b
  Preparing metadata (setup.py) ... done

In [ ]:
!pip install learntools

Requirement already satisfied: learntools in /usr/local/lib/python3.12/dist-packages (0.3.5)

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle (1).json': b'{"username":"motheonkitseng","key":"cebac21760b134dbdaa5df8efee45a5e"}'}

In [ ]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d zynicide/wine-reviews --unzip

Dataset URL: https://www.kaggle.com/datasets/zynicide/wine-reviews
License(s): CC-BY-NC-SA-4.0
Downloading wine-reviews.zip to /content
100% 50.9M/50.9M [00:01<00:00, 28.4MB/s]

In [ ]:
!kaggle datasets download -d zynicide/wine-reviews --unzip

Dataset URL: https://www.kaggle.com/datasets/zynicide/wine-reviews
License(s): CC-BY-NC-SA-4.0
Downloading wine-reviews.zip to /content
100% 50.9M/50.9M [00:01<00:00, 28.9MB/s]

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print("Setup complete.")

Setup complete.

In [ ]:
fruits = pd.DataFrame({'Apples':[30], 'Bananas':[21]})

fruits

   Apples  Bananas
0      30       21

In [ ]:
fruit_sales = pd.DataFrame({
    'Apples':[35,41],
    'Bananas':[21,34],
},  index=['2017 Sales', '2018 Sales'])

fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [ ]:
ingredients = pd.Series(
    ['4 cups', '1 cup', '2 large', '1 can'],
    index=['Flour', 'Milk', 'Eggs', 'Spam'],
    name='Dinner'
)
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
reviews = pd.read_csv('winemag-data_first150k.csv', index_col=0)
reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [ ]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

animals.to_csv('cows_and_goats.csv')

In [ ]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19